In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("diamonds.csv", index_col=0)

In [ ]:
df.head(7)

   carat        cut color clarity  depth  table  price     x     y     z
1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47

In [ ]:
df.tail(7)

       carat        cut color clarity  depth  table  price     x     y     z
53934   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53935   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [ ]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [ ]:
df[["cut", "color", "clarity"]].describe()

          cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

In [ ]:
pd.Series(["cut", "color", "clarity"]).unique()

array(['cut', 'color', 'clarity'], dtype=object)

In [ ]:
%matplotlib

Using matplotlib backend: agg

In [64]:
 histogram = df.hist()